const countries=[['Côte d’Ivoire',/c[oô]te d['’ ]ivoire|ivoirien|abidjan/i],['Bénin',/b[eé]nin|b[eé]ninois|cotonou/i],['Sénégal',/s[eé]n[eé]gal|s[eé]n[eé]galais|dakar/i]];
const sectors=[['Fintech',/fintech|paiement|mobile money|banque|finance/i],['Agriculture',/agri|ferme|rural|cultiv|foodtech/i],['Santé',/sant[eé]|health|m[eé]dical/i],['Éducation',/[eé]ducation|edtech|universit[eé]|formation/i],['Services publics',/gouvernement|public|administration|identit[eé] num[eé]rique|e-gov/i]];
const decode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
const tag=(xml,name)=>decode(xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]);
const link=xml=>tag(xml,'link')||xml.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||tag(xml,'guid');
function parse(xml){return [...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi),...xml.matchAll(/<entry(?:\s[^>]*)?>([\s\S]*?)<\/entry>/gi)].slice(0,40).map(m=>{const x=m[1];return{title:tag(x,'title'),url:link(x),summary:tag(x,'description')||tag(x,'summary')||tag(x,'content'),published:tag(x,'pubDate')||tag(x,'published')||tag(x,'updated')}}).filter(x=>x.title&&x.url)}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function classify(text,list){return list.find(([,rx])=>rx.test(text))?.[0]||null}
async function collect(env){const started=new Date().toISOString();const run=await env.DB.prepare("INSERT INTO collection_runs(started_at,status) VALUES(?,'running') RETURNING id").bind(started).first();let fetched=0,inserted=0;try{const {results:sources}=await env.DB.prepare('SELECT * FROM sources WHERE active=1').all();for(const source of sources){try{const res=await fetch(source.url,{headers:{'User-Agent':'AfricaDigitalPulse/1.0 (+https://africa-digital-pulse.pages.dev)'}});const xml=await res.text();const items=parse(xml);fetched+=items.length;for(const item of items){const text=`${item.title} ${item.summary}`;const country=classify(text,countries);if(!country)continue;const fp=await hash(item.url);const out=await env.DB.prepare(`INSERT OR IGNORE INTO signals(source_id,url,fingerprint,title,summary,published_at,country,sector) VALUES(?,?,?,?,?,?,?,?)`).bind(source.id,item.url,fp,item.title,item.summary.slice(0,1000),item.published?new Date(item.published).toISOString():null,country,classify(text,sectors)).run();inserted+=out.meta.changes||0}await env.DB.prepare('UPDATE sources SET last_fetched_at=?,last_status=? WHERE id=?').bind(new Date().toISOString(),res.status,source.id).run()}catch(e){await env.DB.prepare('UPDATE sources SET last_fetched_at=?,last_status=0 WHERE id=?').bind(new Date().toISOString(),source.id).run()}}await env.DB.prepare("UPDATE collection_runs SET finished_at=?,status='success',fetched=?,inserted=? WHERE id=?").bind(new Date().toISOString(),fetched,inserted,run.id).run();return{ok:true,fetched,inserted}}catch(e){await env.DB.prepare("UPDATE collection_runs SET finished_at=?,status='failed',error=? WHERE id=?").bind(new Date().toISOString(),String(e),run.id).run();throw e}}
export default{async scheduled(_,env,ctx){ctx.waitUntil(collect(env))},async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return Response.json({ok:true,service:'Africa Digital Pulse Collector'});if(u.pathname==='/run'&&request.method==='POST'){if(request.headers.get('Authorization')!==`Bearer ${env.COLLECTOR_TOKEN}`)return new Response('Unauthorized',{status:401});return Response.json(await collect(env))}return new Response('Not found',{status:404})}};
