const countries=[
 ['Afrique',/africa|afrique|african|africain|continent/i],['Côte d’Ivoire',/c[oô]te d['’ ]ivoire|ivory coast|ivoirien|abidjan/i],['Bénin',/b[eé]nin|benin|b[eé]ninois|cotonou/i],['Sénégal',/s[eé]n[eé]gal|senegal|dakar/i],
 ['Nigeria',/nigeria|nigerian|lagos|abuja/i],['Afrique du Sud',/south africa|sud-africain|johannesburg|cape town|pretoria/i],['Kenya',/kenya|kenyan|nairobi/i],['Ghana',/ghana|ghanaian|accra/i],['Rwanda',/rwanda|rwandan|kigali/i],
 ['Maroc',/morocco|maroc|moroccan|casablanca|rabat/i],['Égypte',/egypt|[eé]gypte|cairo|le caire/i],['Tunisie',/tunisia|tunisie|tunis/i],['Algérie',/algeria|alg[eé]rie|algiers|alger/i],['Éthiopie',/ethiopia|[eé]thiopie|addis ababa/i],
 ['Tanzanie',/tanzania|tanzanie|dar es salaam/i],['Ouganda',/uganda|ouganda|kampala/i],['Cameroun',/cameroon|cameroun|douala|yaound[eé]/i],['RDC',/democratic republic of congo|r[eé]publique d[eé]mocratique du congo|\brdc\b|kinshasa/i],
 ['Zambie',/zambia|zambie|lusaka/i],['Zimbabwe',/zimbabwe|harare/i],['Angola',/angola|luanda/i],['Mozambique',/mozambique|maputo/i],['Botswana',/botswana|gaborone/i],['Namibie',/namibia|namibie|windhoek/i],
 ['Maurice',/mauritius|maurice|port louis/i],['Madagascar',/madagascar|antananarivo/i],['Togo',/togo|lom[eé]/i],['Burkina Faso',/burkina faso|ouagadougou/i],['Mali',/mali|bamako/i],['Niger',/\bniger\b|niamey/i],
 ['Guinée',/guinea|guin[eé]e|conakry/i],['Gabon',/gabon|libreville/i],['Congo',/republic of congo|r[eé]publique du congo|brazzaville/i],['Cap-Vert',/cape verde|cap-vert|cabo verde|praia/i],['Sierra Leone',/sierra leone|freetown/i],['Liberia',/liberia|monrovia/i]
];
const sectors=[['Fintech',/fintech|paiement|payment|mobile money|banque|banking|finance/i],['Télécommunications',/telecom|t[eé]l[eé]com|connectivit|broadband|fibre|fiber|5g|satellite|internet/i],['Intelligence artificielle',/artificial intelligence|intelligence artificielle|\bai\b|machine learning|g[eé]n[eé]rative/i],['Cybersécurité',/cyber|ransomware|data protection|protection des donn[eé]es|digital safety/i],['Startups & investissement',/startup|start-up|venture capital|funding|lev[eé]e de fonds|investissement|accelerator/i],['Commerce numérique',/e-commerce|ecommerce|marketplace|commerce num[eé]rique|retail tech/i],['Cloud & infrastructures',/cloud|data cent(er|re)|infrastructure num[eé]rique|digital infrastructure/i],['Agriculture',/agritech|agri-tech|agriculture num[eé]rique|digital agriculture|foodtech/i],['Santé',/healthtech|sant[eé] num[eé]rique|digital health|medtech|t[eé]l[eé]m[eé]decine/i],['Éducation',/edtech|[eé]ducation num[eé]rique|digital education|e-learning/i],['Services publics',/e-gov|egov|gouvernement num[eé]rique|digital government|digital public|identit[eé] num[eé]rique|digital id/i]];
const digital=/digital|num[eé]rique|technolog|innovation|internet|connectivit|t[eé]l[eé]com|fintech|mobile money|paiement|payment|startup|start-up|artificial intelligence|intelligence artificielle|\bai\b|cyber|cloud|data cent(er|re)|e-commerce|ecommerce|platform|plateforme|software|logiciel|satellite|broadband|fibre|fiber|5g|blockchain|crypt|edtech|healthtech|agritech/i;
const decode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
const tag=(xml,name)=>decode(xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]);
const link=xml=>tag(xml,'link')||xml.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||tag(xml,'guid');
function parse(xml){return [...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi),...xml.matchAll(/<entry(?:\s[^>]*)?>([\s\S]*?)<\/entry>/gi)].slice(0,40).map(m=>{const x=m[1];return{title:tag(x,'title'),url:link(x),summary:tag(x,'description')||tag(x,'summary')||tag(x,'content'),published:tag(x,'pubDate')||tag(x,'published')||tag(x,'updated')}}).filter(x=>x.title&&x.url)}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function classify(text,list){const specific=list.find(([name,rx])=>name!=='Afrique'&&rx.test(text));return specific?.[0]||list.find(([,rx])=>rx.test(text))?.[0]||null}
function validDate(value){if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString()}
function isRecent(value){const date=validDate(value);return !date||Date.now()-new Date(date).getTime()<62*86400000}
async function collectSource(source,env){try{const res=await fetch(source.url,{headers:{'User-Agent':'AfricaDigitalPulse/1.0 (+https://pulse.bookemrick.online)'},signal:AbortSignal.timeout(8000)});if(!res.ok)throw new Error(`HTTP ${res.status}`);const items=parse(await res.text());let inserted=0,relevant=0;for(const item of items){const text=`${item.title} ${item.summary}`;if(!digital.test(text)||!isRecent(item.published))continue;const country=classify(text,countries);if(!country)continue;relevant++;const fp=await hash(item.url);const out=await env.DB.prepare(`INSERT OR IGNORE INTO signals(source_id,url,fingerprint,title,summary,published_at,country,sector,last_seen_at) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(source.id,item.url,fp,item.title,item.summary.slice(0,1000),validDate(item.published),country,classify(text,sectors)).run();inserted+=out.meta.changes||0;if(!(out.meta.changes||0))await env.DB.prepare("UPDATE signals SET last_seen_at=CURRENT_TIMESTAMP,status=CASE WHEN status='rejected' THEN 'new' ELSE status END WHERE fingerprint=?").bind(fp).run()}await env.DB.prepare('UPDATE sources SET last_fetched_at=?,last_status=? WHERE id=?').bind(new Date().toISOString(),res.status,source.id).run();return{fetched:items.length,relevant,inserted}}catch(e){await env.DB.prepare('UPDATE sources SET last_fetched_at=?,last_status=0 WHERE id=?').bind(new Date().toISOString(),source.id).run();return{fetched:0,relevant:0,inserted:0,error:String(e)}}}
async function collect(env){const started=new Date().toISOString();const run=await env.DB.prepare("INSERT INTO collection_runs(started_at,status) VALUES(?,'running') RETURNING id").bind(started).first();let fetched=0,relevant=0,inserted=0;try{const {results:sources}=await env.DB.prepare('SELECT * FROM sources WHERE active=1').all();for(let i=0;i<sources.length;i+=4){const results=await Promise.all(sources.slice(i,i+4).map(source=>collectSource(source,env)));for(const result of results){fetched+=result.fetched;relevant+=result.relevant;inserted+=result.inserted}}await env.DB.prepare("UPDATE collection_runs SET finished_at=?,status='success',fetched=?,inserted=? WHERE id=?").bind(new Date().toISOString(),fetched,inserted,run.id).run();return{ok:true,fetched,relevant,inserted,scope:'Afrique · transformation numérique'}}catch(e){await env.DB.prepare("UPDATE collection_runs SET finished_at=?,status='failed',error=? WHERE id=?").bind(new Date().toISOString(),String(e),run.id).run();throw e}}
export default{async scheduled(_,env,ctx){ctx.waitUntil(collect(env))},async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return Response.json({ok:true,service:'Africa Digital Pulse Collector'});if(u.pathname==='/run'&&request.method==='POST'){if(request.headers.get('Authorization')!==`Bearer ${env.COLLECTOR_TOKEN}`)return new Response('Unauthorized',{status:401});return Response.json(await collect(env))}return new Response('Not found',{status:404})}};
